<?php 
    class AdminView extends Admin{
        public function checkCredentials($username, $passwd){
            return $this->checkUserCredentials($username, $passwd);
        }

        public function getUsers()
        {
            return parent::getAdmins(); // TODO: Change the autogenerated stub
        }

        public function countUsers()
        {
            return parent::countUsers(); // TODO: Change the autogenerated stub
        }

        public function getUser($id)
        {
            return parent::getAdmin($id); // TODO: Change the autogenerated stub
        }
    }
?>