<?php
    class GradeView extends Grade{
      public function getAll()
      {
          return parent::getAll(); // TODO: Change the autogenerated stub
      }

      public function get($id)
      {
          return parent::get($id); // TODO: Change the autogenerated stub
      }

        public function count()
      {
          return parent::countGrades(); // TODO: Change the autogenerated stub
      }
    }
?>