<?php
    class GradeController extends Grade{
       public function insert($name, $description)
       {
           return parent::insert($name, $description); // TODO: Change the autogenerated stub
       }

       public function delete($id)
       {
           return parent::delete($id); // TODO: Change the autogenerated stub
       }

    }
?>