<?php
    class MessageController extends Message{
       public function add($id, $sub, $body)
       {
           return parent::insert($id, $sub, $body); // TODO: Change the autogenerated stub
       }

       public function edit($id , $response, $admin)
       {
           return parent::editResponse($id , $response, $admin); // TODO: Change the autogenerated stub
       }

       public function delete($id)
       {
           return parent::deleteMessage($id); // TODO: Change the autogenerated stub
       }

    }
?>