<?php
    class MessageView extends Message{
      public function getAll()
      {
          return parent::getMessages(); // TODO: Change the autogenerated stub
      }

      public function get($id)
      {
          return parent::getMessagesForThisStudent($id); // TODO: Change the autogenerated stub
      }

      public function getMessage($id)
      {
          return parent::getMessage($id); // TODO: Change the autogenerated stub
      }

        public function count()
      {
          return parent::countMessages(); // TODO: Change the autogenerated stub
      }

      public function getStudentMessages($id){
        return parent::getMessagesFor($id);
      }
    }
?>