<?php
    class ProgramView extends Program{
      public function getAll()
      {
          return parent::getAll(); // TODO: Change the autogenerated stub
      }

      public function get($id)
      {
          return parent::get($id); // TODO: Change the autogenerated stub
      }

      public function getPrg($id)
      {
          return parent::getProgram($id); // TODO: Change the autogenerated stub
      }

        public function count()
      {
          return parent::countPrograms(); // TODO: Change the autogenerated stub
      }
    }
?>