<?php
    class ProgramController extends Program{
       public function insert($code , $name, $faculty)
       {
           return parent::insert($code , $name, $faculty); // TODO: Change the autogenerated stub
       }

       public function edit($id, $code , $name, $faculty)
       {
           return parent::edit($id, $code , $name, $faculty); // TODO: Change the autogenerated stub
       }

       public function delete($id)
       {
           return parent::delete($id); // TODO: Change the autogenerated stub
       }

    }
?>