<?php
    class PSView extends PS{
      public function get($programID)
      {
          return parent::get($programID); // TODO: Change the autogenerated stub
      }

      public function getC($programID)
      {
          return parent::getC($programID); // TODO: Change the autogenerated stub
      }

      public function checkExistence($programID, $subjectID)
      {
          return parent::checkExistence($programID, $subjectID); // TODO: Change the autogenerated stub
      }
    }
?>