<?php
    class SSController extends SS{
       public function insert($programID , $subjectID, $gradeID)
       {
           return parent::insert($programID , $subjectID, $gradeID); // TODO: Change the autogenerated stub
       }

       public function delete($id)
       {
           return parent::delete($id); // TODO: Change the autogenerated stub
       }

    }
?>