<?php
    class SSView extends SS{
      public function get($student)
      {
          return parent::get($student); // TODO: Change the autogenerated stub
      }

      public function getC($student)
      {
          return parent::getC($student); // TODO: Change the autogenerated stub
      }

      public function checkExistence($programID, $subjectID)
      {
          return parent::checkExistence($programID, $subjectID); // TODO: Change the autogenerated stub
      }
    }
?>