<?php
    class SubjectController extends Subject{
       public function insert($name, $description)
       {
           return parent::insert($name, $description); // TODO: Change the autogenerated stub
       }

       public function edit($id, $name, $description)
       {
           return parent::editSubject($id, $name, $description); // TODO: Change the autogenerated stub
       }

       public function delete($id)
       {
           return parent::deleteSuject($id); // TODO: Change the autogenerated stub
       }

    }
?>