<?php
    class UserController extends User{
    
       public function edit($id , $name, $email, $password)
       {
           return parent::edit($id , $name, $email, $password); // TODO: Change the autogenerated stub
       }

    }
?>